#!/usr/bin/env lua

--divide-simulate && parse stopkit-sas-link @natreserve | pin-link-excise::dtmen @parse-object set-core-link | bind interface to ntr-trafe ftq && bind-limit::parse
--restore stgen && net-pin satkit Q dtr-mind shaft && pin | source-accit-fund @ bind-integer::stop-core-limit && rebuild
--bind@stellar --inshape-pdr-link=MILD steff-cdven | net.resolv @link-pocket simulate && dn.rts.str.bind.cim pac-link | bind
--rebuild_all

--eof=closed
