#!/usr/bin/env lua

--iden --sat/kit/ntr-trace-limit bts-intake --sym-link @NTnest dfnf-bind --core-symlink | net-reserve @pac-rebuild && kill/off --pin-kit | do ntr_trafe && netreserve --pac-limit::stop-core-ident \ mtr-skim dns-resolv @cliobs-sesslim net-U/mint
--vide-lfdnf --close-sym-link @pac-rebuild to claw ++ sed. limit

--eof=closed

