#!/usr/bin/env lua

--build network--hop && parse to sequel //remit && closed-link ntgemm iq_link rnd //evapp -settuns::gell pic --Umntrs resume::cat --idstgen then build fdEX ++ caserun -misses

--eof=closed
