#!/usr/bin/env lua

--defer-crib=sync ++ ntm-rebuild @pac-limit mnt-tor::sync pac @close --dress-run//kai-fips == parse let-cden-sync::annex-sync.resolv
--let-supply=bind-core-ident && parse

--eof=closed
